## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
arr = np.random.randint(1, 16, size=10)
arr[(arr>3) & (arr<8)] *= -1
arr

array([13, 11,  3, -6, 12, 10,  9, -4, -4,  8])

**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
arr = np.random.randint(1, 21, size=10)
arr

array([18, 18, 10, 18,  2, 15, 20,  1, 17,  4])

In [5]:
arr[arr == arr.max()] = 0
arr

array([18, 18, 10, 18,  2, 15,  0,  1, 17,  4])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [91]:
def func(array):
    arrays = [np.asarray(a) for a in array]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


arr = np.random.randint(0,21, size = (3,3))
print(func(arr))

[[11  5 14]
 [11  5  4]
 [11  5  1]
 [11 16 14]
 [11 16  4]
 [11 16  1]
 [11 18 14]
 [11 18  4]
 [11 18  1]
 [15  5 14]
 [15  5  4]
 [15  5  1]
 [15 16 14]
 [15 16  4]
 [15 16  1]
 [15 18 14]
 [15 18  4]
 [15 18  1]
 [ 5  5 14]
 [ 5  5  4]
 [ 5  5  1]
 [ 5 16 14]
 [ 5 16  4]
 [ 5 16  1]
 [ 5 18 14]
 [ 5 18  4]
 [ 5 18  1]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [118]:
A = np.random.randint(0,10, size=(8,3))
B = np.random.randint(0,10, size=(2,2))

In [119]:
A

array([[5, 9, 3],
       [3, 0, 5],
       [5, 3, 2],
       [3, 8, 2],
       [9, 3, 2],
       [3, 4, 5],
       [3, 0, 0],
       [4, 3, 6]])

In [120]:
B

array([[6, 5],
       [0, 2]])

In [122]:
def func(A: list, B: list) -> list:
    answer = []
    for index, row in enumerate(A):
        if (np.intersect1d(row, B[0]).size > 0) & (np.intersect1d(row, B[1]).size > 0):
            answer.append(index)
    return answer


func(A,B)

[1, 2]

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [203]:
A = np.random.randint(0,2,size=(10,3))
A

array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 1]])

In [204]:
def func_5(A: list):
    output = []
    for index, row in enumerate(A):  
        if np.unique(row).size != 1:
            output.append(A[index])
    return np.stack(output)


func_5(A)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 1]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [2]:
arr = np.random.randint(0,2, size = (10,3))
arr

array([[0, 1, 0],
       [1, 1, 0],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 0],
       [1, 1, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [3]:
np.unique(arr, axis = 0)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0]])

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [6]:
#Numpy solution
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

A = np.diagonal(X)
A[A != 0].prod()

3

In [10]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
prod = 1
for i in range(0, len(X[0])):
    if X[i][i] != 0:
        prod *= X[i][i]
print(prod)

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [19]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

In [20]:
np.array_equiv(np.sort(x), np.sort(y))

True

In [4]:
x = [1, 2, 2, 5]
y = [4, 2, 1, 2]

In [5]:
x.sort()
y.sort()
x == y

False

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [81]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

i = np.where(x == 0)[0] + 1
max(np.take(x, i[i< len(x)]))

5

In [82]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

In [92]:
curr_max = 0
for i, num in enumerate(x):
    if num == 0 and i+1 < len(x) and x[i+1] > curr_max:
        curr_max = x[i+1]
print(curr_max)

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [106]:
x = np.array([2, 2, 2, 3, 3, 3, 5])

y = np.array([np.count_nonzero(x == i) for i in np.unique(x)])
print(np.unique(x), y)

[2 3 5] [3 3 1]


In [107]:
x = [2, 2, 2, 3, 3, 3, 5]

y = [x.count(i) for i in list(set(x))]
print(list(set(x)), y)

[2, 3, 5] [3, 3, 1]


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [158]:
x = np.array([[0,0,0], [1,1,1], [0,0,0], [1,1,1]])
y = np.array([[3,3,3], [3,3,3]])
z = [np.sqrt(sum((x_1 - y_1)**2)) for x_1 in x for y_1 in y]
z

[5.196152422706632,
 5.196152422706632,
 3.4641016151377544,
 3.4641016151377544,
 5.196152422706632,
 5.196152422706632,
 3.4641016151377544,
 3.4641016151377544]

In [164]:
x = [[0,0,0], [1,1,1], [0,0,0], [1,1,1]]
y = [[3,3,3], [3,3,3]]
z = [sum([(c_x - c_y)**2 for c_x, c_y in zip(x_1,y_1)]) ** (1/2) for x_1 in x for y_1 in y]
z

[5.196152422706632,
 5.196152422706632,
 3.4641016151377544,
 3.4641016151377544,
 5.196152422706632,
 5.196152422706632,
 3.4641016151377544,
 3.4641016151377544]

In [6]:
import scipy.spatial
x = np.array([[0,0,0], [1,1,1], [0,0,0], [1,1,1]])
y = np.array([[3,3,3], [3,3,3]])

scipy.spatial.distance.cdist(x, y, metric='euclidean')

array([[5.19615242, 5.19615242],
       [3.46410162, 3.46410162],
       [5.19615242, 5.19615242],
       [3.46410162, 3.46410162]])

In [68]:
#Функция scipy.spatial.distance.cdist() работает быстрее при увеличении размености массивов 
#Размер массива 1000х3: 1.71s (мое решение); 0.007s (scipy.spatial.distance.cdist()) :(
import time
x = [[random.randint(i, i+10) for _ in range(3)] for i in range(1000)]
y = [[random.randint(i, i+10) for _ in range(3)] for i in range(1000)]

for i in range(10):
    start_time = time.time()
    scipy.spatial.distance.cdist(x, y, metric='euclidean')
    print("--- %s seconds ---" % (time.time() - start_time))

--- 0.007002115249633789 seconds ---
--- 0.007001399993896484 seconds ---
--- 0.0070018768310546875 seconds ---
--- 0.007001161575317383 seconds ---
--- 0.007002115249633789 seconds ---
--- 0.007000923156738281 seconds ---
--- 0.007002115249633789 seconds ---
--- 0.0070018768310546875 seconds ---
--- 0.008001327514648438 seconds ---
--- 0.0070018768310546875 seconds ---


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [70]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [71]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [72]:
average_calories = np.average(calorie_stats)
print(f"Среднее кол-во калорий {average_calories}, на {average_calories - 60} больше чем в CrunchieMunchies")

Среднее кол-во калорий 106.88311688311688, на 46.883116883116884 больше чем в CrunchieMunchies


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [5]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [6]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [8]:
nth_percentile = np.percentile(calorie_stats_sorted, q=4)
nth_percentile

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [9]:
more_calories = np.round((calorie_stats_sorted[calorie_stats_sorted > 60].size / calorie_stats_sorted.size)* 100, 2)
more_calories

96.1

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [10]:
calorie_std = np.std(calorie_stats_sorted)
calorie_std

#standart error = std/sqrt(n) = 2,14
#confidence interval (95%) = mean +- 1,96 SE

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [73]:
# Согласно полученным данным, можно утверждать, что 96.1% других злаков являются более калорийными.
# Всего 3 продукта конкурентов имеют меньшую калорийность
# Средняя калорийность идентичных продуктов - 110 (медиана), 106.88 (среднее) со стандартным отклонением 19,36 калорий.

SyntaxError: unterminated string literal (detected at line 3) (3602613082.py, line 3)